### ISSUE TITLE
Feature Idea: Video Prediction

### ISSUE THREAD

**Issue by M-Colley** [vita-epfl/bounding-box-prediction#1]
Hey, thanks for sharing your work!

Would it be possible to implement the prediction and visualizing it in "in the wild" videos?
I understand that the code would have to detect the bounding boxes of pedestrians and their speed and input this in the model, correct?
Are there any intentions to provide such functionality or some hints how to do this?

Kind regards!

**Comment by SaeedSaadatnejad** [comment]
Hi,
sorry for answering late. Thank you for your interest in this work.
Yes, the model can be extended to any dataset but it needs the bounding boxes for the observation.
You can run any off-the-shelf method to detect the bounding boxes and then feed this info to our model to predict.
