### ISSUE TITLE
you are losing the batch information

### ISSUE THREAD

**Issue by Cram3r95** [vita-epfl/bounding-box-prediction#13]
![imagen](https://user-images.githubusercontent.com/15740838/181195675-71f9c3ee-1820-4015-8a92-75738a781cea.png)

Why do you do this? You are losing your batch information, since you go from:

obs_len x batch_size x 2

To:

obs_len x hidden_dim

This does not make sense.

**Comment by SaeedSaadatnejad** [comment]
Hello,

Which part of the code are you referring to? As far as I see, nothing is lost about the batch_size. Only a permutation is done to make the dimensions correct for lstm encoders.
