### ISSUE TITLE
Can I run JAAD dataset alone with current version of the model?

### ISSUE THREAD

**Issue by Pawako-002** [vita-epfl/bounding-box-prediction#17]
I have noticed that this model uses 3 datasets from JAAD, JTA to NuScenes; may I ask if the current version of the model on GitHub is able to run JAAD alone (excluding JTA and NuScenes) ? At this stage I only want to run JAAD dataset, do I need to modify any files to do that?

**Comment by SaeedSaadatnejad** [comment]
Hi, yes it should work without modifications.
