### ISSUE TITLE
How can I visualize JAAD?

### ISSUE THREAD

**Issue by yuuuu10603** [vita-epfl/bounding-box-prediction#18]
Thanks for your code. I have some question. How can I visualize JAAD? 
[Like these pictures](https://github.com/vita-epfl/bounding-box-prediction/blob/master/Images/visualizations.png)
Thank you.

**Comment by SaeedSaadatnejad** [comment]
Unfortunately, the visualization code for JAAD has been misplaced. 
But with a few minor adjustments to the Nuscenes visualization code, you can make it work for JAAD as well.

**Comment by yuuuu10603** [comment]
> Unfortunately, the visualization code for JAAD has been misplaced. But with a few minor adjustments to the Nuscenes visualization code, you can make it work for JAAD as well.

OK. I will try. Thank you.
