### ISSUE TITLE
Removing all crossing labels?

### ISSUE THREAD

**Issue by 17sarf** [vita-epfl/bounding-box-prediction#3]
https://github.com/vita-epfl/bounding-box-prediction/blob/25da3c2c6165048d59b5b08c87205c9a7778511b/DataLoader.py#L110

Doesn't this line remove any `labels` that are not `1` (crossing),  effectively only leaving only `0` (not crossing)? I may not be understanding this properly, please correct me if I'm wrong.

Thanks in advance.

**Comment by xuguilin0802** [comment]
> https://github.com/vita-epfl/bounding-box-prediction/blob/25da3c2c6165048d59b5b08c87205c9a7778511b/DataLoader.py#L110
> 
> Doesn't this line remove any `labels` that are not `1` (crossing), effectively only leaving only `0` (not crossing)? I may not be understanding this properly, please correct me if I'm wrong.
> 
> Thanks in advance.

My dear friend，I have the same question.Do you know the reason now?

**Comment by SaeedSaadatnejad** [comment]
It removes the pedestrians that are already on the road (obs).
If the observation of someone shows he/she is on the road, the intention prediction is easy and we aim to predict the intention sufficiently in advance.

**Comment by xuguilin0802** [comment]
> It removes the pedestrians that are already on the road (obs). If the observation of someone shows he/she is on the road, the intention prediction is easy and we aim to predict the intention sufficiently in advance.

Wow, thanks for your reply, it really helps me a lot.Best wishes to you
