### ISSUE TITLE
Visualisation of the result

### ISSUE THREAD

**Issue by ameeeeena** [vita-epfl/bounding-box-prediction#4]
Hi, thank you for sharing your work.

i want to make prediction and its visualization on a video: 

1. would you propose to me an available and efficient bounding box detector's code to use?

2. How to feed this code into the model, like where should i make changes so it works ?

Best regards,

**Comment by SaeedSaadatnejad** [comment]
Hi, thank you for showing interest in our work.
1. There are many works e.g. you can refer to openpifpaf developed by our lab which detects pose and bounding box too.
2. If you mean how to feed the bb detection to this code: you need to use that code in the beginning of this code. The detected bb are fed as input to our proposed model and it predicts the next bounding boxes.
Let me know if you still have ambiguities.

Best regards,
Saeed

**Comment by ameeeeena** [comment]
Hi,
Yes actually i still have ambiguities...

i checked out openpifpaf, (https://github.com/openpifpaf) but got lost there, i couldn't know the bbox detection code i need to feed to this code

best,

**Comment by SaeedSaadatnejad** [comment]
Hi,

It provides pose and bb at the same time. In the output files (JSON files), you can observe bb along with pose info for all humans in the image.
About the details of openpifpaf, you can ask your questions in their repository. You can also refer to any object/human detection code.

Best,
Saeed
