### ISSUE TITLE
How to visualize the outputs of the network?

### ISSUE THREAD

**Issue by boumedienemohammed** [vita-epfl/bounding-box-prediction#5]
Hi @SaeedSaadatnejad,

Thank you for this repository :100:  

We are working on your interesting paper entitled "Pedestrian Intention Prediction: A Multi-task Perspective".

Please can you help us to visualize (plot bounding-box and its label) the outputs of the network on each image as you have done in the following image :

![/Images/visualizations.png](https://github.com/vita-epfl/bounding-box-prediction/blob/master/Images/visualizations.png)

We know that it can be possible to do it by modifying the "test.py" file but we didn't understand some outputs as:
https://github.com/vita-epfl/bounding-box-prediction/blob/ccdd9511054fd3c97ab38d4b6ad5d4b960ec43a0/test.py#L87-L89
**obs_s** is the computed speed for each pedestrian ? calculated as [new position given by the detector] - [last estimated position] ?   
**obs_p** is  the new position (of each pedestrian) given by the detector?
**speed_preds** is the estimated speed given by the network? 
**crossing_preds** is the estimated position given by the network? we think that estimated positions are calculated after at line 99?
**intentions** is the predicted intention given by the network?

https://github.com/vita-epfl/bounding-box-prediction/blob/ccdd9511054fd3c97ab38d4b6ad5d4b960ec43a0/test.py#L91-L97
**Does this code compute the error on the estimated position "crossing_preds"? or the intersection between bounding-boxes?**
https://github.com/vita-epfl/bounding-box-prediction/blob/ccdd9511054fd3c97ab38d4b6ad5d4b960ec43a0/test.py#L99-L103
**pres_p represents the estimated position? what about ade, fde, aiou, fiou?**
https://github.com/vita-epfl/bounding-box-prediction/blob/ccdd9511054fd3c97ab38d4b6ad5d4b960ec43a0/test.py#L105-L114
**label_c represents the ground-truth? and intentions represents the estimated/predicted intention?**

**what about state_preds,  state_targets,   intent_preds, intent_targets?

### In advance, THANK YOU for your help

**Comment by SaeedSaadatnejad** [comment]
Hello,

obs_s is the sequence of speeds for each pedestrian, calculated as [current position] - [last position]
obs_p is the sequence of positions of each pedestrian
speed_preds is the sequence of predicted speeds (the first head of the network)
crossing_preds is the sequence of predicted states and intentions contains the predicted value for each sequence showing the intention of that pedestrian (the second head of the network)
As you said, the absolute positions are calculated in line 99.

Question: Does this code compute the error on the estimated position "crossing_preds"? or the intersection between bounding-boxes?
Answer: It computes both errors: 1) the first lines (L91-94 and L97) compute the error of the intention prediction head 2) the error of the predicted speed of bounding boxes compared to the ground truth is added to the loss in L96

Question: pres_p represents the estimated position? what about ade, fde, aiou, fiou?
Answer: pred_p is the absolute predicted position of the bounding boxes which should be compared with the ground truth in two aspects 1)ade, fde for the center of bb 2) aiou and fiou for the intersection of bbs

Question: label_c represents the ground-truth? and intentions represents the estimated/predicted intention?
**what about state_preds, state_targets, intent_preds, intent_targets?
Answer: label_c is the ground truth and intentions represents the predicted intention which should be compared with.
Other lists just accumulate all previous lists.


Hope it answers and sorry that the code was not clear enough.

Best regards,
Saeed Saadatnejad

**Comment by boumedienemohammed** [comment]
Thank you :+1: :+1: :+1: , 

Your responses helped us a lot to understand the outputs of your net but surely we will have other questions next days.

Best regards,
