### ISSUE TITLE
imbalanced cross/ not cross labels

### ISSUE THREAD

**Issue by jinxing94** [vita-epfl/bounding-box-prediction#6]
I do not know why I find that only about 10% samples are with cross labels.  Could you help check the ratio of positive samples ?

If the data is indeed imbalanced, other metrics like the recall, f1-score of intention prediction may be important.

**Comment by SaeedSaadatnejad** [comment]
Hello,

I don't know the exact ratio but it is true that there are fewer crossing pedestrians in the dataset.
Indeed, what you suggested (reporting recall and f1-score) is a very good idea for a comprehensive study. We only reported the accuracy and compared it with previous works.

Best,
Saeed
