### ISSUE TITLE
hello sir i'm really new to AI so excuse me for my ignorance but what are the jaad_path , train_ration,val_ratio,test_ratio 

### ISSUE THREAD

**Issue by hi574** [vita-epfl/bounding-box-prediction#7]

**Comment by SaeedSaadatnejad** [comment]
Hello,

Jaad_path is the path to the jaad dataset, train_ratio indicates the ratio of the train set compared to the whole dataset. test_ratio and val_ratio indicate similar variables for test and validation sets. These arguments should be given to the code when you run prepare_data.py
